#!/usr/bin/env bash

: ${WALTER_ROOT:=./build/lib/walter}

# KtoA
export KATANA_RESOURCES=${KTOA_ROOT}
export KATANA_POST_PYTHONPATH=${KTOA_ROOT}/python
export ARNOLD_PLUGIN_PATH=${KTOA_ROOT}/procedurals
export ARNOLD_PLUGIN_PATH=${KTOA_ROOT}/shaders:${ARNOLD_PLUGIN_PATH}:${MTOA_ROOT}/shaders
export ARNOLD_SHADERLIB_PATH=${ARNOLD_PLUGIN_PATH}

# Walter
export ARNOLD_PLUGIN_PATH=${WALTER_ROOT}/arnold
export KATANA_RESOURCES=${WALTER_ROOT}/katana:${KATANA_RESOURCES}
export LD_LIBRARY_PATH=${WALTER_ROOT}/arnold

${KATANA_ROOT}/katana $@
