// Copyright 2017 Rodeo FX. All rights reserved.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Convert a text file to a cpp file with c++ string containing the source. It's
// necessary to include the source to the binary.

int main(int argc, const char* argv[])
{
    const char* fileNameSrc = NULL;
    const char* fileNameDst = NULL;

    const char** arg = &fileNameSrc;
    int i;
    for (i = 1; i < argc; i++)
    {
        if (!strcmp(argv[i], "-h") || !strcmp(argv[i], "--help"))
        {
            printf(
                "Converts any file to the C source file\n"
                "USAGE:\n"
                "%s source -o destination\n",
                argv[0]);
        }

        if (!strcmp(argv[i], "-o"))
        {
            arg = &fileNameDst;
            continue;
        }

        *arg = argv[i];
        arg = &fileNameSrc;
    }

    if (!fileNameSrc)
    {
        printf("Error: The source is not specified\n");
        return 1;
    }

    if (!fileNameDst)
    {
        printf("Error: The destination is not specified\n");
        return 1;
    }

    /* Form the name of the variable and the function. */
    char* name = strdup(fileNameSrc);

    const char* badChars = "/\\.-+<>";
    char* badOne;
    char* p;
    for (badOne = badChars; *badOne != '\0'; badOne++)
    {
        for (p = name; (p = strchr(p, *badOne)); ++p)
        {
            *p = '_';
        }
    }

    /* Open the files. */
    FILE* fileSrc = fopen(fileNameSrc, "rb");
    FILE* fileDst = fopen(fileNameDst, "w");

    /* First line of the file. */
    fprintf(fileDst, "/* Generated with Walter resourcer. */\n\n");
    fprintf(fileDst, "#include \"pxr/base/tf/registryManager.h\"\n\n");
    fprintf(fileDst, "#include \"pxr/base/tf/type.h\"\n\n");
    fprintf(fileDst, "#include \"rdoCustomResource.h\"\n\n");

    /* Declare the variable. */
    fprintf(fileDst, "static const unsigned char %s_begin[] = {", name);

    /* Generate the byte code. */
    int counter = 0;
    unsigned char current = '\0';
    while (!feof(fileSrc))
    {
        if (counter++ % 16 == 0)
        {
            fprintf(fileDst, "\n");
        }

        fread(&current, 1, 1, fileSrc);
        fprintf(fileDst, "0x%02x, ", current);

        // 'current' needs to be set to a null character. This is because on last 
        // call to fread (when we are at the end of the file) previous value is
        // used (probably a compiler optimisation). 
        // For example if the last char is a '}', without this line it would add
        // it twice leading to an error while trying to compile the souce code 
        // from the generated byte code (like when glCompileShader() is called).
        current = '\0';
    }

    /* The final 0 symbol. */
    fprintf(fileDst, "0x00};\n");

    /* The function that returns the string. */
    fprintf(
        fileDst,
        "PXR_NAMESPACE_USING_DIRECTIVE;\n"
        "TF_REGISTRY_FUNCTION(TfType)\n"
        "{\n"
        "setResource(\"%s\", (const char*)&%s_begin[0]);\n"
        "}\n",
        fileNameSrc,
        name);

    fclose(fileSrc);
    fclose(fileDst);

    free(name);

    return 0;
}
