set(ZLIB_NAMES z zlib zdll zlib1)
find_library(
    ZLIB_LIB
    NAMES ${ZLIB_NAMES}
    HINTS ${ZLIB_ROOT}
    PATH_SUFFIXES lib
    NO_DEFAULT_PATH)

SET( ALEMBIC_ZLIB_LIBS ${ZLIB_LIB} )

MESSAGE(STATUS "ZLIB INCLUDE PATH: ${ZLIB_INCLUDE_DIR}" )
MESSAGE(STATUS "ZLIB LIBRARIES: ${ALEMBIC_ZLIB_LIBS}" )

