// Copyright 2017 Rodeo FX.  All rights reserved.

// Export a Usd layer with some transforms and check if the time sample 2 value is good.
proc int _testExportTransforms(string $dirIn, string $dir, string $geoFile) 
{
    string $nodePath = $dirIn + $geoFile;
    string $node = wCreateStandin($nodePath);
    
    // Create animated transform
    walterStandin -exposeTransform $node "/pCube1/pCube3";
    select -r pCube1;
    setKeyframe -breakdown 0 -hierarchy none -controlPoints 0 -shape 0 {"pCube1"};
    currentTime 2 ;
    setAttr "pCube1.translateZ" -5;
    setKeyframe -breakdown 0 -hierarchy none -controlPoints 0 -shape 0 {"pCube1"};

    // Save transforms
    string $xfoLayerFile = $dir + $geoFile + ".usda";
    walterStandin -saveTransforms $node $xfoLayerFile -startTime 1 -endTime 2 -simulationRate 1;
    
    return _readAndFindInFile($xfoLayerFile, "2: ( (1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, -5, 1) ),");;
}

global proc int testExportTransforms()
{   
    string $dir = "/tmp/testExportTransforms/";
    string $dirIn = dirname(wGetCurrentDir()) + "/resources/alembics/";

    sysFile -makeDir $dir;
    int $success = _testExportTransforms($dirIn, $dir ,"cubes.abc");
    prDeleteFolder($dir);

    if($success)
    {
        return 0;
    }

    return 1;
}

