// Copyright 2017 Rodeo FX.  All rights reserved.

#ifndef __ENGINE_H__
#define __ENGINE_H__

#include <pxr/usd/sdf/path.h>
#include <string>

#include "delegate.h"
#include "index.h"
#include "plugin.h"

PXR_NAMESPACE_USING_DIRECTIVE

// The top-level entry point for rendering USD stage. We have one object per
// stage.
class RendererEngine
{
public:
    // Public constructor.
    static RendererEngine* getInstance(
        const std::string& fileName,
        const std::vector<std::string>& layers);
    // Remove all the cached RendererEngine objects.
    static void clearCaches();

    // Number of nodes that is generated by the specified path.
    int getNumNodes(const SdfPath& path, const std::vector<float>& times);

    // Generate a render node for the specified path.
    void* render(
        const SdfPath& path,
        int id,
        const std::vector<float>& times,
        const void* userData);

private:
    friend class std::pair<const std::string, RendererEngine>;

    // We need to be sure that this object can be created only by registry.
    RendererEngine(
        const std::string& fileName,
        const std::vector<std::string>& layers);

    // Prepare index.
    void prepare(const UsdPrim& root);

    RendererPlugin mPlugin;
    RendererIndex mIndex;
    RendererDelegate mDelegate;

    UsdStageRefPtr mStage;
};

#endif
